import { api } from "../shared/api";
export const getMyTurfs = () => api.get("/owners/turfs/me");
export const getTurfById = (id) => api.get(`/owners/turfs/me/${id}`);
export const addTurf = (fd) => api.post("/owners/turfs/addTurf", fd);
export const updateTurf = (id, data) => api.put(`/owners/turfs/update/${id}`, data);
export const addTurfImages = (turfId, files) => {
    const fd = new FormData();
    files.forEach(f => fd.append("images", f));
    return api.post(`/owners/turfs/${turfId}/images`, fd);
};
export const deleteTurfImage = (turfId, imageId) => api.delete(`/owners/turfs/${turfId}/images/${imageId}`);
export const deleteTurf = (id) => api.delete(`/owners/turfs/delete/${id}`);
export const saveTurfSchedule = (id, data) => api.post(`/owners/turfs/${id}/schedule`, data);
export const generateSlots = (id) => api.post(`/owners/turfs/slots/generate/${id}`);
export const getSlots = (id, date) => api.get(`/owners/turfs/slots`, { params: { turfId: id, date } });
export const updateSlotStatus = (id, data) => api.patch(`/owners/turfs/slots/status/${id}`, data);
export const getTurfSchedule = (id) => api.get(`/owners/turfs/${id}/schedule`);
export const getOwnerBookings = () => api.get("/owner/bookings");
export const getOwnerBookingDetails = (bookingId) => api.get(`/owner/bookings/${bookingId}`);
export const getOwnerBalance = () => api.get("/owner/ledger/balance");
export const getNextPayout = () => api.get("/owner/ledger/pending");
export const getPaymentHistory = () => api.get("/owner/ledger/history");
export const getWeeklyLedger = (start, end) => api.get("/owner/ledger/weekly-ledger", { params: { start, end } });
